name: "Code Convention Check"
description: "Enforce Silicon Labs C/C++ coding standards (formatting, naming, spelling)"

inputs:
  exclude-regex:
    description: |
      Regex pattern to exclude paths from all checks.
      Format: Python regex, use | for OR.
      Example: .*\/generated\/.*|.*\.pb\.c
    required: false
    default: ""

  codespell-ignore-words:
    description: |
      Words for codespell to ignore.
      Format: Comma-separated, case-insensitive.
      Example: hsi,aci,dout,teh
    required: false
    default: ""

  codespell-skip-paths:
    description: |
      Files/directories for codespell to skip.
      Format: Comma-separated glob patterns (fnmatch-style), not regex. Avoid using **.
      Example: *.bin,docs/*,third_party/*
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Build Code Convention Docker Image
      shell: bash
      run: |
        docker build -t coding-convention-tool:${{ github.sha }} ${{ github.action_path }}

    - name: Run Code Convention Checks
      shell: bash
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/src" \
          -e EXCLUDE_REGEX="${{ inputs.exclude-regex }}" \
          -e CODESPELL_IGNORE_WORDS="${{ inputs.codespell-ignore-words }}" \
          -e CODESPELL_SKIP_PATHS="${{ inputs.codespell-skip-paths }}" \
          coding-convention-tool:${{ github.sha }}

    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: CodingConventionResult
        path: ${{ github.workspace }}/CodingConventionTool.txt
        retention-days: 3

    - name: Upload Patch
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: code-fix.patch
        path: ${{ github.workspace }}/code-fix.patch
        retention-days: 3
